### PR TITLE
Pristine vendor

### PR DESCRIPTION
**Pull request by sykesm**
Running `govendor sync` resulted in a number of pending changes to the repository. This restores the vendored dependencies to their pristine state, excludes the govendor cache directory from git, and updates the scripts that run `go fmt` to excluded vendored code.

### CODE REVIEW

**Comment by sykesm** [comment]
#201 should address the build failure

**Comment by maximilien** [comment]
Thanks for contribution @sykesm.

Hi, @zhanggbj,

Please ensure this passes your new pipeline and I will merge. Looks like it should.

Note to all that the Beijing team is on holiday for Chinese New Year so their responses might not be immediate. They are all back to work on Jan 6th.

**Comment by zhanggbj** [comment]
@maximilien Sorry for late response, verified with our pipeline and all BATs passed. Thanks.
(Release Commit 7628ac2)

/cc @mattcui

**Comment by maximilien** [comment]
Cool. Merging. Thanks @sykesm and @zhanggbj

**Pull request merged**
